# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#Advincula
#Tranquilan

#### 1. Import the numpy package under the name `np`


In [4]:
import numpy as np

#### 2. Print the numpy version

In [2]:
print (np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [11]:
null_array = np.zeros(5)

print(null_array)

[0. 0. 0. 0. 0.]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [12]:
null_arr = np.zeros(15)

null_arr[6] = 1

print(null_arr)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [42]:
matrix = np.arange(16).reshape(4, 4)

print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [15]:
arr = np.array([1, 2, 4, 0, 4, 0])

non_zero_indices = np.nonzero(arr)

print(non_zero_indices)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [16]:
random_array2 = np.random.rand(4, 4, 4)

print(random_array2)

[[[0.5238645  0.07635711 0.51694949 0.17844939]
  [0.85454353 0.04327767 0.02672859 0.02319169]
  [0.73076896 0.55542236 0.84378951 0.72725103]
  [0.64942179 0.62746913 0.04702639 0.58411909]]

 [[0.35232054 0.6007553  0.79540518 0.79546696]
  [0.31925477 0.95961904 0.32132138 0.92744223]
  [0.12970329 0.45303468 0.02790034 0.41150545]
  [0.5755919  0.97467797 0.93909372 0.0886676 ]]

 [[0.37088088 0.88094673 0.4613637  0.1356902 ]
  [0.55788573 0.68301562 0.51738605 0.36029873]
  [0.74180034 0.60077427 0.06685025 0.63188353]
  [0.32878808 0.89797499 0.08520687 0.9833103 ]]

 [[0.6750417  0.70629122 0.06781166 0.70304197]
  [0.51436791 0.63483189 0.30656948 0.07186257]
  [0.55050929 0.93836257 0.45184343 0.94587489]
  [0.49374647 0.4346507  0.36218054 0.59111934]]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [17]:
random_array1 = np.random.rand(15, 15)

min_value = np.min(random_array1)
max_value = np.max(random_array1)

print("Random 15x15 array:")
print(random_array1)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)

Random 15x15 array:
[[0.62008999 0.3446856  0.8135564  0.35126078 0.35159943 0.0206349
  0.26548941 0.16350067 0.88868337 0.983421   0.03357532 0.29135004
  0.68409442 0.85441591 0.50223184]
 [0.54322117 0.07189341 0.7438927  0.44442036 0.19485533 0.68161707
  0.24943035 0.74741544 0.09776737 0.77050409 0.60947111 0.29880828
  0.83612821 0.86169268 0.27741398]
 [0.46710345 0.97863461 0.69137725 0.40879126 0.65608921 0.10906239
  0.58083284 0.32470352 0.91698753 0.32324568 0.7149701  0.61869775
  0.05778826 0.96032698 0.49294948]
 [0.07446763 0.69952348 0.88387105 0.49184405 0.35639785 0.46601138
  0.79647    0.11169675 0.51411474 0.60954692 0.06689136 0.98001806
  0.43962868 0.10525325 0.10061425]
 [0.70180188 0.15981575 0.64675679 0.09452468 0.30333932 0.93052641
  0.2359426  0.777513   0.00424512 0.39115744 0.79225553 0.71628807
  0.81541384 0.886357   0.56043194]
 [0.55737479 0.86205532 0.19192188 0.41718278 0.08444112 0.40876095
  0.29340591 0.47065528 0.44950486 0.53868656 0.68743

#### 9. Create a random array of size 25 and find the mean value

In [18]:
random_array = np.random.rand(25)

mean_value = np.mean(random_array)

print("Random array of size 25:")
print(random_array)
print("\nMean value:", mean_value)

Random array of size 25:
[0.37807841 0.89703047 0.02555269 0.97627985 0.11281683 0.27140803
 0.38213504 0.23100952 0.07617664 0.10539578 0.5612873  0.81938628
 0.12297311 0.19804693 0.20609765 0.92740518 0.26386733 0.39632734
 0.58271092 0.41948094 0.13122521 0.78253983 0.15088719 0.13896872
 0.45758205]

Mean value: 0.3845867691223171


#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [21]:
array1 = np.array([12, 4, 9])
array2 = np.array([11, 14, 6])

print("Array1:", array1)
print("Array2:", array2)

Array1: [12  4  9]
Array2: [11 14  6]


10.1 What is the result of *a + b*?

In [22]:
result_add = array1 + array2
print("a + b:", result_add)

a + b: [23 18 15]


10.2 What is the result of *a - b*?

In [23]:
result_subtract = array1 - array2
print("a - b:", result_subtract)

a - b: [  1 -10   3]


10.3 What is the result of *a × b*?

In [24]:
result_multiply = array1 * array2
print("a * b:", result_multiply)

a * b: [132  56  54]


10.4 What is the result of *a ÷ b*?

In [25]:
result_divide = array1 / array2
print("a / b:", result_divide)

a / b: [1.09090909 0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [11]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) * 10

print(matrix1)   

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [12]:
print(matrix1[1,1])

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [13]:
second_row = matrix1[1, :]

print(second_row)

[40 50 60]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [15]:
third_column = matrix1[:, 2]

print(third_column)

[30 60 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [17]:
submatrix = matrix1[1:3, 1:3]

print(submatrix)

[[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [18]:
matrix2 = np.arange(1, 13).reshape(3, 4)

print(matrix2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [20]:
subarray = matrix2[1:3, 1:3]

print(subarray)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [21]:
first_row_elements = matrix2[0, ::2]

print(first_row_elements)

[1 3]


4. Write code to reverse the order of rows in the matrix

In [22]:
reversed_matrix = matrix2[::-1]

print(reversed_matrix)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


5. Write code to extract the last two columns of the matrix.

In [24]:
last_two_columns = matrix2[:, -2:]

print(last_two_columns)

[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [25]:
arr1, arr2 = np.array([11, 7, 33]), np.array([44, 5, 18])

print("Array1:", arr1)
print("Array2:", arr2)  

Array1: [11  7 33]
Array2: [44  5 18]


2. Write code to join arr1 and arr2 into a single 1D array.

In [27]:
joined_array = np.concatenate((arr1, arr2))

print("Joined array:", joined_array)

Joined array: [11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [32]:
stacked_array = np.stack((arr1, arr2), axis=0)

print("Stacked array:")
print(stacked_array)

Stacked array:
[[11  7 33]
 [44  5 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [35]:
arr3, arr4 = np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]])

print("Array1:\n", arr3)
print("Array2:\n", arr4)

Array1:
 [[1 2]
 [3 4]]
Array2:
 [[5 6]
 [7 8]]


5. Write code to join them horizontally (column-wise).

In [36]:
horizontal_stack = np.hstack((arr3, arr4))

print("Horizontally stacked array\n:" , horizontal_stack)

Horizontally stacked array
: [[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [37]:
vertical_stack = np.vstack((arr3, arr4))

print("Vertically stacked array:\n", vertical_stack)

Vertically stacked array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [40]:
arr5, arr6, arr7 = np.arange(10, 29, 2), np.random.randint(1, 51, (4, 4)), np.ones((2, 3, 4))

print("1D Array:\n", arr5)
print("\n2D Array:\n", arr6)
print("\n3D Array:\n", arr7)

1D Array:
 [10 12 14 16 18 20 22 24 26 28]

2D Array:
 [[ 7  1 38 18]
 [25 36 43 33]
 [16  3  6 39]
 [ 1 39 39 22]]

3D Array:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [46]:
print("Reshaped 1D array to 2D (2 rows):")
print(arr5.reshape(2, -1))

print("\nLast two rows of the 2D array:")
print(arr6[-2:])

print("\n2D array with even numbers replaced by -1:")
print(np.where(arr6 % 2 == 0, -1, arr6))

Reshaped 1D array to 2D (2 rows):
[[10 12 14 16 18]
 [20 22 24 26 28]]

Last two rows of the 2D array:
[[16  3  6 39]
 [ 1 39 39 22]]

2D array with even numbers replaced by -1:
[[ 7  1 -1 -1]
 [25 -1 43 33]
 [-1  3 -1 39]
 [ 1 39 39 -1]]


### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [48]:
mean_value, median_value, std_deviation = np.mean(arr6), np.median(arr6), np.std(arr6)
sum_rows = np.sum(arr6, axis=1)
max_value, max_index = np.max(arr6), np.unravel_index(np.argmax(arr6), arr6.shape)

print(f"Mean: {mean_value}, Median: {median_value}, Standard Deviation: {std_deviation}")
print(f"Sum of all elements along each row: {sum_rows}")
print(f"Maximum value: {max_value}, Index of maximum value: {max_index}")


Mean: 22.875, Median: 23.5, Standard Deviation: 15.111564280378124
Sum of all elements along each row: [ 64 137  64 101]
Maximum value: 43, Index of maximum value: (np.int64(1), np.int64(2))


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.

In [50]:
arrayy = np.random.rand(10, 10)

minmin_values = np.min(arrayy, axis=0)
top_5_indices = np.unravel_index(np.argsort(arrayy.ravel())[-5:], arrayy.shape)

print(f"Minimum values along each column: {minmin_values}")
print(f"Indices of the top 5 largest values: {top_5_indices}")

Minimum values along each column: [0.20601301 0.01855887 0.0132625  0.206185   0.02928069 0.11327818
 0.00913122 0.13517129 0.04365589 0.07628439]
Indices of the top 5 largest values: (array([6, 7, 2, 6, 6]), array([1, 7, 3, 6, 3]))
